### ISSUE TITLE
As a Software Engineer I want user personas so I can have empathy towards the end user. 

### ISSUE THREAD

**Issue by MVita11** [Entropic-Visio/swe-pioneers#39]
I've done the user persona. If you guys want to check it out and see whether it is up to standard, please do

**Comment by Entropic-Visio** [comment]
Acceptance Criteria
- I need you to create some personas for sprint 2
- Create 3 Personas with different requirements
- Make sure that they are brief and makes sense
- We can use them to create user stories.

**Comment by Entropic-Visio** [comment]
Sorry I mean I need images/templated personas so we can scim them.

**Comment by Entropic-Visio** [comment]
User Persona isn't completed, still needs a bit more, but will close once finsishjed.

**Comment by Entropic-Visio** [comment]
👍Compelted.
