### ISSUE TITLE
As a Software Engineers we need class Diagrams so we can understand how our classes function and are related

### ISSUE THREAD

**Issue by Cinnamon-Bread** [Entropic-Visio/swe-pioneers#45]
Description: As software engineers, class diagrams serve as indispensable navigational tools in comprehending the intricacies of our codebase. These visual representations offer a bird's-eye view of how classes function and relate to one another within the software architecture. By decoding the relationships, dependencies, and interactions encapsulated in these diagrams, we gain invaluable insights into the overall structure of our system, facilitating more effective collaboration, troubleshooting, and the evolution of robust and scalable software solutions.

**Comment by Entropic-Visio** [comment]
👍 Looks good closing the issue now.
